Migrate from pin-project to pin-project-lite
sdroege/async-tungstenite pull request #76
Opened 2021-01-08 16:26 UTC by nickelc

`pin-project-lite` does not support tuple structs. So, it's a breaking change because `TokioAdapter` and its inner type is public.  

Closes: #75

2021-01-08 19:09 UTC, nickelc commented
> Is there a reason to have the inner type public?

I found some projects that construct TokioAdapter

[bsundsrud/minuteman/blob/.../src/coordinator.rs#L144]
[pajbot/tweet-provider/blob/.../src/websocket.rs#L75]
[iburinoc/socket.io-client-rs/blob/.../socket-io-client/examples/ws_connect.rs#L37]
https://github.com/najamelan/ws_stream_tungstenite

[bsundsrud/minuteman/blob/.../src/coordinator.rs#L144]: https://github.com/bsundsrud/minuteman/blob/effe266677871e2ebf3161c41eefcde9f0085132/src/coordinator.rs#L144
[pajbot/tweet-provider/blob/.../src/websocket.rs#L75]: https://github.com/pajbot/tweet-provider/blob/5c45c38a3e1a8634753d4c5384a9055c40afc99b/src/websocket.rs#L75
[iburinoc/socket.io-client-rs/blob/.../socket-io-client/examples/ws_connect.rs#L37]: https://github.com/iburinoc/socket.io-client-rs/blob/b3779364424a29b9667828da16c8704527852223/socket-io-client/examples/ws_connect.rs#L37

2021-01-09 09:09 UTC, sdroege requested changes
The reason why it was public is that this is a simple wrapper type and that way it was nicest to be used. But adding explicit constructor/destructors here is OK too if it improves compile times considerably in practice.

2021-01-09 09:09 UTC, sdroege commented on src/tokio.rs
> +    pub(crate) fn new(inner: T) -> Self {
```suggestion
    pub fn new(inner: T) -> Self {
```

It's needed for providing custom tokio `AsyncRead`/`AsyncWrite` as the underlying stream of the websocket.

2021-01-09 09:09 UTC, sdroege commented on src/tokio.rs
> +        Self { inner }
Can you also add a public `into_inner()`?

2021-01-09 10:12 UTC, sdroege approved these changes

2021-01-09 10:26 UTC, merged